[package]
name = "mdbook-snippets"
version = "0.1.0"
edition = "2021"

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[dependencies]
clap = "4.5"
mdbook = "=0.4.40"
serde_json = "1.0"
